# Generated by Django 3.2.4 on 2021-07-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_session', models.CharField(blank=True, max_length=100, null=True)),
                ('AdSense_CPC', models.CharField(blank=True, max_length=100, null=True)),
                ('AdSense_CTR', models.CharField(blank=True, max_length=100, null=True)),
                ('AdSense_Campaign_level_revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_Revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('RPM', models.CharField(blank=True, max_length=100, null=True)),
                ('Coverage', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campign_Site_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Taboola_Click', models.CharField(blank=True, max_length=100, null=True)),
                ('Taboola_CPC', models.CharField(blank=True, max_length=100, null=True)),
                ('CPC', models.CharField(blank=True, max_length=100, null=True)),
                ('CTR', models.CharField(blank=True, max_length=100, null=True)),
                ('Daily_Campain_Level_Site_Spend', models.CharField(blank=True, max_length=100, null=True)),
                ('Campain_Site_Level_Bid_Changing', models.CharField(blank=True, max_length=100, null=True)),
                ('Site_Block_Unblock_Capign_Level', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camping_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Campaign_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Taboola_Clicks', models.CharField(blank=True, max_length=100, null=True)),
                ('Campaign_CTR', models.CharField(blank=True, max_length=100, null=True)),
                ('Taboola_Campaign_Level_CPC', models.CharField(blank=True, max_length=100, null=True)),
                ('Daily_Spend', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Google_Analytics_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session', models.CharField(blank=True, max_length=100, null=True)),
                ('AdSense_CPC', models.CharField(blank=True, max_length=100, null=True)),
                ('CPC', models.CharField(blank=True, max_length=100, null=True)),
                ('CTR', models.CharField(blank=True, max_length=100, null=True)),
                ('Revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('Coverage', models.CharField(blank=True, max_length=100, null=True)),
                ('Daily_Spend', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
