# Generated by Django 3.2.4 on 2021-07-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camping_level',
            name='json_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
